[build]
  command = "npm run build"
  publish = "dist" 

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

# Trỏ api/vocab về file vocab.ts
[[redirects]]
  from = "/api/vocab"
  to = "/.netlify/functions/vocab"
  status = 200

# Trỏ api/import-vocab về file import-vocab.ts
[[redirects]]
  from = "/api/import-vocab"
  to = "/.netlify/functions/import-vocab"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200